# Generated by Django 4.1.7 on 2023-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_moviedata_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(default="images/noimage.png", upload_to="images/"),
        ),
    ]
